- CHANGELOG.md
- src/command/crf_search.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/vmaf.rs
Add optional `--vmaf-options <OPTIONS>` argument to _vmaf, sample-encode, crf-search, auto-encode_ commands. This string is passed to ffmpeg `libvmaf='<OPTIONS>'`, see https://ffmpeg.org/ffmpeg-filters.html#libvmaf.
```text
ab-av1 vmaf ... --vmaf-options n_threads=8:n_subsample=4:log_path=./vmaf.log
```
> Add `--vmaf-options` argument

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/command.rs
- src/command/args.rs
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/encode.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/ffprobe.rs
- src/process.rs
- src/svtav1.rs
Add svt-av1 arguments:
- `--keyint FRAME-OR-DURATION` argument supporting frame integer or duration string, _e.g. `--keyint=300` or `--keyint=10s`_.
- `--scd` argument enabling scene change detection.
- `--svt ARG` for additional args, _e.g. `--svt mbr=2000 --svt film-grain=30`_.
> Add svt-av1 arguments `--keyint`, `--scd`, `--svt`

- CHANGELOG.md
- src/command/args.rs
- src/command/args/svt.rs
- src/command/crf_search.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/vmaf.rs
* Add vmaf configuration `--vmaf ARG`, _e.g. `--vmaf n_threads=8 --vmaf n_subsample=4`_.
This is more consistent with the `--svt ARG` for svt-av1 options. Plus should be more flexible if we want to move to directly invoking vmaf instead of using ffmpeg later.
> Replace --vmaf-options with --vmaf ARG

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/command/args.rs
Explicitly set vmaf n_threads to all logical cores unless it is provided manually in a `--vmaf` arg.
This should address #9 issue with the upstream default not using call cores.
> Default vmaf n_threads to the number of CPUs

- .github/workflows/ci.yml
- CHANGELOG.md
- src/command/args/svt.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/ffprobe.rs
- src/svtav1.rs
- src/vmaf.rs
- src/yuv.rs
* Add `--vfilter` argument to apply a ffmpeg video filter (crop, scale etc) to the input before av1 encoding.
* Add _vmaf_ command `--reference-vfilter` argument, similar to `--vfilter`.
Resolves #10
> Add `--vfilter` & vmaf `--reference-vfilter`

- CHANGELOG.md
- src/command/args.rs
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/encode.rs
- src/command/sample_encode.rs
- src/main.rs
- src/sample.rs
- src/svtav1.rs
- src/temporary.rs
- src/yuv.rs
Create samples concurrently with encoding to prevent slow io stalls
crf-search re-use samples for all crfs
Resolves #6
> Add --temp-dir argument

- CHANGELOG.md
- Cargo.lock
- src/command/args.rs
- src/command/args/svt.rs
- src/command/encode.rs
- src/ffprobe.rs
- src/svtav1.rs
* Add `--downmix-to-stereo` option, if enabled & the input streams use > 3 channels (dts 5.1 etc), downmix input audio streams to stereo.
> Add `--downmix-to-stereo` flag

- CHANGELOG.md
- Cargo.lock
- src/command/encode.rs
When defaulting the output file don't use input extension if it is _avi, y4m, ivf_, use mp4 instead.
> Don't use avi, y4m, ivf extensions in default output

- .github/workflows/ci.yml
- .gitignore
- CHANGELOG.md
- Cargo.toml
- README.md
- deploy
- src/command/args/svt.rs
- src/command/args/vmaf.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/ffprobe.rs
- src/vmaf.rs
* Add `--vmaf-width` option which sets the video resolution width to use in VMAF analysis.
* When using the default VMAF model, improve VMAF accuracy for sub-1k resolutions by defaulting
`--vmaf-width=1920` whenever video resolution width is less than 1728. This will result in lower 
VMAF scores than were reported for such videos in previous versions.
* Strip debug symbols in release builds by default which reduces binary size _(requires rustc 1.59)_.
Resolves #27
> Vmaf upscale lower resolutions to 1080p + add `--vmaf-width` option

- CHANGELOG.md
- src/command/auto_encode.rs
- src/command/crf_search.rs
* Fix clearing _crf-search_ progress bar output on error.
* Add predicted video stream percent reduction to _auto-encode_ search progress bar after a successful search.
Resolves #30
> crf-search keep bar after fail, auto-encode show percent

- CHANGELOG.md
- src/command/args/svt.rs
- src/command/args/vmaf.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/ffprobe.rs
Add `--vmaf-scale` option which sets the video resolution scale to use in VMAF analysis. May be set to `auto` auto scale based on model & resolution, `none` no scaling or custom `WxH` format, e.g. `1920x1080`. `auto` should be best unless a custom model is being used.
Resolves #32
> Rework vmaf-width into vmaf-scale

- CHANGELOG.md
- src/command/args/vmaf.rs
Select vmaf model `model=version=vmaf_4k_v0.6.1` for videos larger than 2560x1440 if no other model is specified. 
Also default vmaf-scale to upscale videos to 4k when the model is selected in a similar way as is done for the default 1k model.
Resolves #28
> Use 4k model for larger video automatically

- CHANGELOG.md
- src/command/sample_encode.rs
- src/sample.rs
Improve sample speed & duration accuracy, see https://github.com/alexheretic/ab-av1/issues/36#issuecomment-1146634936
Resolves #36 
Closes #38
> Use -ss input & -frames:v instead of -t

- CHANGELOG.md
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/crf_search/err.rs
When running `auto-encode` command each crf attempt is not printed. This mean if no suitable crf is found it isn't clear how close the attempts got.
This pr adds the info from the final crf attempt as the progress bar message coloured red for the failing bits.
```
Searching 00:00:11 ################## (sampling crf 32, eta 0s)
Error: Failed to find a suitable crf
```
```
Searching 00:00:11 ################## (crf 32, VMAF 92.99, size 7%)
Error: Failed to find a suitable crf
```
Resolves #35
> auto-encode: show last attempt crf when failing

- CHANGELOG.md
- Cargo.lock
- README.md
- src/command/args/encode.rs
- src/command/auto_encode.rs
- src/command/encode.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/ffmpeg.rs
- src/ffprobe.rs
This PR addresses #56.
Instead of erroring on input media with an unknown duration, we set it to zero and then treat all zero-length media as images.
There are currently some `unwrap`s that I'm not too happy about, but it "works on my machine™".
> Add AVIF support

- CHANGELOG.md
- src/command/auto_encode.rs
- src/command/encode.rs
- src/command/sample_encode.rs
* Fix overridden `--encoder` .avi file samples using the same extension, which will generally not work.
Such samples will now encode to .mp4 in the same way _encode_ already did in this case.
Related to another issue mentioned in #63
> Fix ffmpeg avi sample extensions

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/vmaf.rs
- src/yuv.rs
Brings windows in line with Linux for VMAF both converting reference & distorted into yuv streams before passing to libvmaf.
Gives more consistently accurate results and brings Windows in line with Linux functionality.
Resolves #65
Resolves #63
> Implement windows named pipe vmaf

- CHANGELOG.md
- Cargo.lock
- src/command/sample_encode.rs
When sampling use full input video when sample time would be >= 85% of the total (down from 100%).
Resolves #71
> Sampling: Use full input video when sample time is 85%

- CHANGELOG.md
- src/command/args.rs
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/encode.rs
- src/command/sample_encode.rs
- src/ffmpeg.rs
- src/svtav1.rs
New logic for determining output & ffmpeg sample output extension/container.
* If -o is specified use the same extension.
* If input is .mp4 use .mp4.
* Otherwise use .mkv.
Resolves #72
> Default output to .mkv

- CHANGELOG.md
- src/ffmpeg.rs
- src/svtav1.rs
Encode mkv outputs with the "cues" seek index at the front to optimise stream usage.
I was going to do this later... but then I just did it.
Resolves #76
> Encode mkv outputs with the "cues" seek index at the front

- CHANGELOG.md
- Cargo.lock
- src/sample.rs
Uses mkv (or mp4) for the temporary 20s lossless sample "copies" created for encode+VMAF analysis. Previously the input extension was used, however mkv/mp4 should provide better compatibility.
See #70 discussion.
Also prepare changelog for v0.5.0 release.
Resolves #70
> Use mkv/mp4 for all 20s sample copies

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
Automatically build and add **ab-av1.exe** binaries to new releases. The first one should turn up for **v0.5.0**.
Resolves #75
> Auto build ab-av1.exe releases

- CHANGELOG.md
- Cargo.lock
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/sample_encode.rs
- src/process.rs
* Change encoded size prediction logic to estimate video stream size only. Change text to clarify this.
* Improve video size prediction logic to account for samples that do not turn out as 20s.
May resolve #79
> Predict video stream size instead of file size

- CHANGELOG.md
- src/command/args/encode.rs
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/encode.rs
- src/command/sample_encode.rs
- src/ffmpeg.rs
- src/process.rs
- src/svtav1.rs
Supports using decimal crf in _sample-encode_ & _encode_ subcommands.  Note svt-av1 only supports integer crf. _crf-search_ remains an integer search.
See #83
> Support decimal crf in sample-encode, encode

- CHANGELOG.md
- Cargo.lock
- src/sample.rs
Use mkv containers for all lossless samples. Previously mp4 samples were used for mp4 inputs, however in all test cases mkv 20s samples were better quality. This change improves accuracy for all mp4 input files.
See [test results & analysis](https://github.com/alexheretic/ab-av1/issues/82#issuecomment-1337306325).
> Use mkv for all lossless samples

- CHANGELOG.md
- src/command/args/encode.rs
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/crf_search/err.rs
- src/ffmpeg.rs
- src/float.rs
- src/main.rs
* Add _crf-search_, _auto-encode_ arg `--crf-increment`. Previously this would always be 1.
Defaults to **1**. -e libx264, libx265 & libvpx-vp9 default to **0.1**.
* Add _crf-search_, _auto-encode_ arg `--thorough` which more exhaustively searches to find
a crf value close to the specified min-vmaf.
Resolves #83
> Add crf-search `--crf-increment` & `--thorough` args: Allow decimal crf search

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/command/args/encode.rs
- src/command/crf_search.rs
- src/command/sample_encode.rs
- src/command/sample_encode/cache.rs
- src/ffmpeg.rs
- src/svtav1.rs
By default cache _sample-encode_ results in `$CACHE_DIR/ab-av1` directory using sled db.
Each result is keyed by `$RESULT_HASH`, computed using:
* sample file name
* input duration
* input extension
* input size
* encoder args
* `SvtAv1EncApp --version` (if applicable).
This mean they should be reasonably unique without requiring a full read of the input.
Caching _sample-encode_ results allows repeating runs of _crf-search_ perhaps with different `--min-vmaf` args etc. The cache will avoid the same crfs having to be re-encoded. 
If a _crf-search_ touches only pre-encoded crf values it'll finish pretty instantly.
```
$ ab-av1 crf-search -i test-vids/pixabay-lemon-82602.mp4 --preset 12 --min-vmaf 95
- crf 32 VMAF 95.87 (18%) (cached)
- crf 43 VMAF 92.08 (8%) (cached)
- crf 35 VMAF 94.95 …
```
> Cache sample-encode results

- CHANGELOG.md
- src/ffmpeg.rs
The nvenc hardware encoders use -cq for target quality/vbr rate control.  Add the minimal arg logic to support this family of encoders.
This allows use of av1_nvenc, hevc_nvenc, and h264_nvenc.
```
C:\Video>ab-av1 auto-encode -i ToS-4k-1920.mov --encoder av1_nvenc
Encoding ToS-4k-1920.av1_nvenc.mkv
Searching 00:00:47 #################################################################### (crf 39, VMAF 95.35, size 19%)
Encoding  00:00:27 ################################################################################# (638 fps, eta 0s)
Encoded 128.97 MiB (18%, video:117.59 MiB, audio:11.05 MiB)
```
Additional features such as custom arguments are already supported.
```
C:\Video>ab-av1 crf-search -i ToS-4k-1920.mov --encoder av1_nvenc --preset p7 --enc rc-lookahead=32 --min-vmaf 96 --thorough …
```
> Add support for nvenc family of ffmpeg encoders

- CHANGELOG.md
- src/command/sample_encode/cache.rs
- src/ffmpeg.rs
- src/main.rs
- src/sample.rs
- src/temporary.rs
Use segregated process-unique temp directory sub-dirs.
Add 2s blocking for cache locking.
Resolves #94
> Support concurrent running processes

- CHANGELOG.md
- src/sample.rs
Automatically workaround ffmpeg _"Can't write packet with unknown timestamp"_ sample generation failures (typically encountered with old avi files) by using \`-fflags +genpts\`.
Fixes #111
> Use -fflags +genpts workaround for failing samples (e.g. .avi)

- CHANGELOG.md
- src/command/args/encode.rs
- src/ffmpeg.rs
A simple arg adding to support QSV encoders.
Maybe it would also be better to enable lookahead by default with HandBrake's default paramenters 
(-look_ahead 1 -lookahead-depth 40) 
https://handbrake.fr/docs/en/latest/technical/video-qsv.html
> Add QSV encoders support 

- CHANGELOG.md
- src/command/args/encode.rs
Actually in the HandBrake page I used to pick up the default value it uses the arg `-lookahead-depth`, but for ffmpeg it is `-look_ahead_depth <int>` which should also be enabled with the `extbrc` flag for encoders other than h264. (https://github.com/alexheretic/ab-av1/pull/121#issuecomment-1456032523)
> Fix args qsv look ahead

- CHANGELOG.md
- Cargo.lock
- src/command/args/encode.rs
- src/command/crf_search.rs
- src/ffmpeg.rs
Add `-e librav1e` support. Map `--crf` to ffmpeg `-qp` (default max 255), `--preset` to `-speed` (0-10).
Resolves #124
> Support librav1e

- CHANGELOG.md
- Cargo.lock
- src/command/args/encode.rs
Disallow `--enc svtav1-params=` usage. libsvtav1 params should instead be set with `--svt`. Currently using it just won't work properly.
```
$ ab-av1 crf-search  ... --enc svtav1-params=film-grain=6
error: invalid value 'svtav1-params=film-grain=6' for '--enc <ENC_ARGS>': 'svtav1-params' cannot be set here, use `--svt`
```
Resolves #128
> Deny --enc svtav1-params

- Cargo.lock
- Cargo.toml
See:
- <https://docs.rs/crate/serde_derive/1.0.176/source/>
- <https://docs.rs/crate/serde_derive/1.0.185/source/>
- <https://github.com/serde-rs/serde/commit/110af31b48c86084721885930065da7d47654ca0>
> Fix: unreproducible precompiled binary in serde_derive

- src/command/args/encode.rs
Fix validation preventing use of --svt args starting with "-i", e.g. "-irefresh-type".
> Fix validation preventing use of --svt args starting with "-i"

- CHANGELOG.md
- src/command/args/vmaf.rs
- src/command/sample_encode.rs
- src/command/sample_encode/cache.rs
Changing VMAF args such as `model`, `pool` - even resolution - results in different scores. These should therefor be included in the cache key.
Things still not reflected:
- Change in VMAF version
- Change in default model used by VMAF (because ab-av1 doesn't set it and I see no trivial way to detect it)
- Change in model used hardcoded by ab-av1 (if that changes, we still could invalidate all the hashes since it's very likely that none of the scores match anymore)
> Hash VMAF args for cache

- .github/workflows/release.yml
Setup CI to build and add ` ab-av1-vX.Y.Z-x86_64-unknown-linux-musl.tar.zst` to future releases.
Resolves #170
> Build linux musl releases

- CHANGELOG.md
- Cargo.lock
- src/command.rs
- src/command/crf_search.rs
- src/command/encode.rs
- src/command/sample_encode.rs
Workaround to resolve #174. This PR tries to set progress bar lengths large to provide as frequent integer progress as possible. This allows the upstream eta calculation to work much better.
So, for example, use `µs / total_µs` instead of `s / total_s` as progress bar units.
> Improve eta by providing more granular progress bar position updates

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/command/args/vmaf.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/vmaf.rs
Use a single ffmpeg process to calculate VMAF replacing multi process piping.
Previously separate ffmpeg processes were used to convert pixel format and to run --reference-vfilter. This PR changes this to a single ffmpeg call with appropriate `-filter_complex` args.
A simple vmaf call will now use -filter_complex something like:
```
[0:v]format=yuv420p10le,setpts=PTS-STARTPTS[dis];[1:v]format=yuv420p10le,setpts=PTS-STARTPTS[ref];[dis][ref]libvmaf=n_threads=16
```
This simplifies the code removing platform specific piping code. It also should make vmaf results easier to reproduce by users.
> Use a single ffmpeg process to calculate VMAF

- CHANGELOG.md
- src/command/args.rs
- src/command/crf_search.rs
- src/command/sample_encode.rs
- src/main.rs
For me it's very useful to look at the generated samples for manual verification. This command works on my machine right now.
@alexheretic please tell me if you want the flag refactored into `args::Sample`. Its probably better that way, right?
> Add `--keep` flag to `crf-search` subcommand

- Cargo.lock
- Cargo.toml
- src/command/args.rs
- src/command/args/encode.rs
Fix #180
Fixed on [upstream](https://github.com/clap-rs/clap/pull/5336) and updated clap_complete.
> Fix filename completion

- CHANGELOG.md
- Cargo.lock
- src/process.rs
Improve failing ffmpeg stderr printing: 
- Don't allow many '\r'-ending updates to cause all other stored info to be truncated. 
- Increase max heap storage of output ~4k->32k to allow more complete output in some cases.
> Improve failing ffmpeg stderr printing

- src/command/args/vmaf.rs
- src/vmaf.rs
Remove the input option `-r` from ffmpeg command and rely on PTS of the respective containers. Add `settb` filter to establish common timebase for different containers.
Different timestamp syncing:
Use the absolute nearest timestamp for frame selection in libvmaf. Also stop at the end of the shortest stream, which sometimes helps with n_subsample>1 when, for some reason, ffmpeg fails with no score to parse. Both options can be overridden by `--vmaf`.
In case the VMAF score obtained using this new approach are lower than expected, adding `--vmaf ts_sync_mode=default` should be tried.
This is supposed to address some issues (#108, #141) which, this author believes, are due to (periodic) de-synchronization of frames in libvmaf caused by rounding errors in the timestamp calculation. It should …
> vmaf: Don't force input frame rate.

- CHANGELOG.md
- Cargo.lock
- src/command/args/encode.rs
> Clarify --vfilter doc further

- CHANGELOG.md
- Cargo.lock
- src/command/crf_search.rs
* crf-search: Tweak 2nd iteration logic that slices the crf range at the 25% or 75% crf point.
- Widen to 20%/80% to account for searches of the "middle" two subranges being more optimal.
- Disable when using custom min/max crf ranges under half the default.
The 2nd iter logic is a bit arcane and not at all obvious to the user. In future this should probably be configurable.
Relates to discussions in #227, #232
So for default settings:
1. Try 32 
2. Assuming 32 failed, try 19 (previously 21)
* If failed try min-crf = 10
* If success linear interpolate next crf between in range (19, 32)
The slight widening means more searches will get to linear interpolation on 3rd iter (those that 21 would have failed on). Though those 21 would have passed on will have slightly worse linear interpolated …
> crf-search: 2nd iteration 20/80 only on default min/max crf & vmaf>=94

- CHANGELOG.md
- Cargo.lock
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/crf_search/err.rs
- src/command/sample_encode.rs
- src/vmaf.rs
* Add sample-encode info to **crf-search**. Show sample `N/M` run progress and encoding/vmaf fps.
```
⠤ 00:00:30 crf 19 1/2 ###############################----------- (vmaf 19 fps, eta 77s)
```
* Similarly add sample-encode info to **auto-encode**.
```
⠂ 00:00:51 crf 31 2/2 ########################################## (VMAF 95.03, size 21%)
⠤ 00:00:09 Encoding #######------------------------------------------- (12 fps, eta 3m)
```
* Tweak sample-encode progress bar format to be more consistent.
Resolves #219
> Include sample encoding info and fps in crf-seach & auto-encode progress bars

- CHANGELOG.md
- src/command/args/vmaf.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/vmaf.rs
Allow setting vmaf fps, ie `-r` ffmpeg input arg for both reference & distorted inputs. 
Relates to #238
> Add `--vmaf-fps`

- CHANGELOG.md
- src/command/args/encode.rs
- src/command/crf_search.rs
- src/ffmpeg.rs
mpeg2video: map `--crf` to ffmpeg `-q` and set default crf range to 2-30.
```
$ ab-av1 crf-search -i vid.mp4 -e mpeg2video --max-encoded-percent 300
- crf 16 VMAF 83.56 (84%) (cache)
- crf 8 VMAF 91.74 (143%) (cache)
- crf 2 VMAF 97.33 (485%) (cache)
- crf 5 VMAF 94.43 (209%) (cache)
00:00:00 crf 4 1/1 ##################################################### (eta 0s)
Encode with: ab-av1 encode -e mpeg2video -i vid.mp4 --crf 4
crf 4 VMAF 95.61 predicted video stream size 52.16 MiB (259%) taking 1 second
```
> Add defaults for mpeg2video encoder

- CHANGELOG.md
- Cargo.lock
- README.md
- src/command.rs
- src/command/args.rs
- src/command/args/vmaf.rs
- src/command/auto_encode.rs
- src/command/crf_search.rs
- src/command/sample_encode.rs
- src/command/sample_encode/cache.rs
- src/command/vmaf.rs
- src/command/xpsnr.rs
- src/main.rs
- src/process.rs
- src/vmaf.rs
- src/xpsnr.rs
- Add sample-encode `--xpsnr` arg which toggles use of XPSNR instead of VMAF.
- Add crf-search, auto-encode `--min-xpsnr` arg _(alternative to `--min-vmaf`)_.
- Add `xpsnr` command for measuring XPSNR score.
```
$ ab-av1 sample-encode -i vid.mp4 --crf 32 --xpsnr
- Sample 1 (65%) XPSNR 41.59
00:00:12 Sample 1/1 ################################################ (xpsnr 117 fps, eta 0s)
Encode with: ab-av1 encode -i vid.mp4 --crf 32
XPSNR 41.59 predicted video stream size 13.18 MiB (65%) taking 18 seconds
```
```
$ ab-av1 crf-search -i vid.mp4 --min-xpsnr 41
- crf 32 XPSNR 41.59 (65%) (cache)
- crf 46 XPSNR 37.73 (26%)
00:00:25 crf 34 1/1 ############################################################### (eta 0s)
Encode with: ab-av1 encode -i vid.mp4 --crf 34
crf 34 XPSNR 41.06 predicted video …
```
> Add XPSNR support as a VMAF alternative

- CHANGELOG.md
- src/command/args/vmaf.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
Default `-r 25` for reference & distorted inputs in all vmaf analysis. This can be disabled with `--vmaf-fps 0`.
Resolves #238
> Default `--vmaf-fps` to 25

- CHANGELOG.md
- src/vmaf.rs
> Omit audio, subtitle & data streams in VMAF calls to work around possible ffmpeg memory leaks

- CHANGELOG.md
- Cargo.lock
- src/command/args/encode.rs
- src/ffmpeg.rs
* Encoder *_vaapi: Default args `--enc-input hwaccel=vaapi --enc-input hwaccel_output_format=vaapi`.
* Encoder *_vulkan: Map `--crf` to ffmpeg `-qp`.
* Encoder *_vulkan: Default args `--enc-input hwaccel=vulkan --enc-input hwaccel_output_format=vulkan`.
Resolves #294
> *_vulkan: use map crf to -qp, provide default input args for vulkan & vaapi encoders

- CHANGELOG.md
- Cargo.lock
- src/command/args/encode.rs
- src/command/args/vmaf.rs
- src/command/sample_encode.rs
- src/command/vmaf.rs
- src/ffmpeg.rs
`--pix-format` no longer generally defaults to "yuv420p", instead if not specified no -pix_fmt will be passed to ffmpeg allowing use of upstream defaults.
However, libsvtav1, libaom-av1 & librav1e will continue to default to "yuv420p10le".
> Remove `--pix-format` yuv420p default behaviour

- CHANGELOG.md
- Cargo.lock
- src/command/args/encode.rs
Allow specifying ffmpeg decoder using `--enc-input c:v=CODEC`.
Resolves #300
> Allow specifying ffmpeg decoder using `--enc-input c:v=CODEC`

- CHANGELOG.md
- Cargo.lock
- src/command/args/encode.rs
Support setting `--enc-input hwaccel=none --enc-input hwaccel_output_format=none` to omit defaults for *_vaapi, *_vulkan vcodecs introduced in v0.9.4.
> Support omitting enc-input defaults for vaapi, vulkan
